# Generated by Django 4.1.5 on 2023-01-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appestudiantes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Instituto',
        ),
    ]
