# Generated by Django 4.1.5 on 2023-01-17 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appestudiantes', '0002_delete_entregable_delete_instituto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='comision',
            new_name='curso',
        ),
    ]
